### ISSUE TITLE
px,rem,em解释

### ISSUE THREAD

**Issue by Kelichao** [Kelichao/mobile.html5#3]
# HTML节点初始字体大小是16px 

# px
```
px：逻辑像素
一个px相当于一个像素
```
# em
```
em:相对的长度单位

1.  em 相对参照物为父元素的font-size
2.  em具有继承的特性，一直会找祖先节点设定了font-size的元素,如果所有的元素都没有设置font-size时，
    浏览器会有一个默认的em设置：1em = 16px;
```

# rem 
```
1. rem的相对参照物为根元素html,相对于em参照固定不变，所以比较好计算。
2. 当没有设置font-size时，浏览器会有一个默认的rem。设置：1rem = 16px，这点与em是一致的。
```

- rem的灵活运用
```css
	html {
		font-size:62.5%;  /* 1rem = 10px (10/16*100%) 
		这样写可以轻松调出各种需要的像素字体大小
		比如我要17px的字体，则元素填1.7rem即可
		*/
	}
```
