### ISSUE TITLE
媒体查询语法规则@media

### ISSUE THREAD

**Issue by Kelichao** [Kelichao/mobile.html5#7]
# 媒体查询语法

<table>
    <tr>
        <td>媒体类型</td>
        <td>常用媒体查询参数</td>
    </tr>
    <tr>
        <td>srcreen(屏幕)</td>
        <td>width(视口宽度)</td>
    </tr>
        <tr>
        <td>print(打印机)</td>
        <td>height(视口高度)</td>
    </tr>
    <tr>
        <td>handheld(手持设备)</td>
        <td>device-width(设备的宽度)</td>
    </tr>
    <tr>
        <td>all(通用)</td>
        <td>device-height(设备的高度)</td>
    </tr>
    <tr>
        <td>--</td>
        <td>orientation(检查设备处于横向landscape，竖屏protrait)</td>
    </tr>
</table>

### 1.声明宽度代表的是实际的像素宽度
- 注：里面填写的max-width/min-width是指实际的渲染宽度，而且媒体查询在任何模式下都生效
- 注：媒体查询中括号里面具体填写的宽度不要用相对长度rem，取得的是浏览器默认的16px字体
```css
@media only screen and (min-width: 320px) and (max-width: 416px){
    html{
        font-size: 12px;
    }
 }
```
### 2.样式生效范围包含当前写的范围点
- 如果两个样式集合有min-width=480与max-width:480;,那么两个样式集合在页面为480px时同时生效
```css
	/*	生效范围0 - 800px */	
	@media only screen and (max-width: 800px) {

	}

	/* 生效范围481 - 800px */
	@media only screen and(min-width:481px) and (max-width: 800px) {

	}

	/* 生效范围0 - 480 */
	@media only screen and (max-width: 480px) {

	}
```
### 注意and与逻辑括号之间必须要有空格
- screen and这后面必须跟一个空格，不然整个语法无效
```css
        /* 整个语法不生效 */
	@media only screen and(min-width:400px) and (max-width: 800px) {
		body{background:blue;}
	}
```
## 需要考虑的最小屏幕分辨率
> 最小的屏幕分辨率现在调整为  320px

## srcset控制图片加载的大小
- 这个规则很复杂，只需了解
```html
<img src="img/480.png" 
	srcset="img/400.png 480w, img/800.png 880w, img/1600.png 1600w">
```
